// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/assets/_404.tsx";
import * as $1 from "./routes/assets/_app.tsx";
import * as $2 from "./routes/assets/api/joke.ts";
import * as $3 from "./routes/assets/greet/[name].tsx";
import * as $4 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/assets/_404.tsx": $0,
    "./routes/assets/_app.tsx": $1,
    "./routes/assets/api/joke.ts": $2,
    "./routes/assets/greet/[name].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
